### ISSUE TITLE
проблема с ARTM_example_RU 

### ISSUE THREAD

**Issue by iDevPro** [bigartm/bigartm-book#53]
Добрый день, проблема с ARTM_example_RU :(

```python
test_batch_vectorizer = artm.BatchVectorizer(data_format='batches', data_path='kos_test', batches=['test_docs.batch'])
test_theta_matrix = model_artm.transform(batch_vectorizer=test_batch_vectorizer)
print(test_theta_matrix)
```

```bash
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/Users/iqqator/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/iqqator/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/iqqator/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/iqqator/anaconda3/lib/python3.6/site-packages/bigartm-0.9.0-py3.6.egg/artm/master_component.py", line 923, in transform
    theta_matrix_info = self._lib.ArtmRequestTransformMasterModelExternal(self.master_id, args)
  File "/Users/iqqator/anaconda3/lib/python3.6/site-packages/bigartm-0.9.0-py3.6.egg/artm/wrapper/api.py", line 161, in artm_api_call
    self._check_error(result)
  File "/Users/iqqator/anaconda3/lib/python3.6/site-packages/bigartm-0.9.0-py3.6.egg/artm/wrapper/api.py", line 97, in _check_error
    raise exception_class(error_message)
artm.wrapper.exceptions.InvalidOperationException: Transform: no batches to process
```

**Comment by iDevPro** [comment]
нужно создать файл test_docs.batch с текстовым содержимым

**Comment by iDevPro** [comment]
Reopen,
how to create test_docs.batch ?

**Comment by MelLain** [comment]
This notebook is outdated, see official guide
http://docs.bigartm.org/en/stable/tutorials/python_userguide/index.html
